name: Publish

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  BUILD_DIR: "${{ github.workspace }}/build/"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly

      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/llvm
          key: llvm-16.0
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "16.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
          directory: ${{ runner.temp }}/llvm
      - name: Symlink libclang.so
        run: sudo ln -s libclang-16.so.1 /lib/x86_64-linux-gnu/libclang.so
        working-directory: ${{ runner.temp }}/llvm

      - uses: katyo/publish-crates@v2
        with:
          path: ./rich-sdl2-rust-sys
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          args: --features vendor
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          args: --features vendor

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: rust.yml
          name: doc-artifact

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
